open-space-collective/open-space-toolkit-astrodynamics

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Utilities/IterableConverter.hpp
- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Utilities/MapConverter.hpp
This fixes a small memory leak in converters. 
Reference counting seems wrong in the `convertible` function: if the iterator from `PyObject_GetIter` is not null, it is never deleted. The change makes sure the new reference is decremented.
Resource: https://www.oreilly.com/library/view/python-cookbook/0596001673/ch16s04.html (cf. Discussion)
> Fix reference counting in converters

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Access.cpp
- bindings/python/test/test_access.py
- include/OpenSpaceToolkit/Astrodynamics/Access.hpp
- src/OpenSpaceToolkit/Astrodynamics/Access.cpp
- src/OpenSpaceToolkit/Astrodynamics/Access/Generator.cpp
- test/OpenSpaceToolkit/Astrodynamics/Access.test.cpp
- Add `maxElevation` `Angle` field on object `Access`. 
- Currently `maxElevation` value is computed using the elevation angular value obtained at TCA (approx.).
> feat: add maximum elevation field on Access

- README.md
- docker/development/debian/Dockerfile
- docker/development/fedora/Dockerfile
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit/Models/SGP4.cpp
The SGP4 upstream repo introduced breaking changes today, and this repo was tracking the `master` branch. This PR adapts to these changes and locks the version.
> fix: SGP4 dependency

- bindings/python/test/trajectory/orbit/models/sgp4/test_tle.py
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit/Models/SGP4/TLE.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit/Models/SGP4/TLE.test.cpp
- Spaces and Zeroes are both valid to pad for revolution number. Aligning to use spaces to match SpaceTrack convention. 
- Zeroes are used for International Designator and Epoch. Already verified.
> chore:  use spaces to pad revolution number for TLE sanitization

- include/OpenSpaceToolkit/Astrodynamics/NumericalSolver.hpp
- src/OpenSpaceToolkit/Astrodynamics/NumericalSolver.cpp
- test/OpenSpaceToolkit/Astrodynamics/Flight/System/Dynamics/AtmosphericDrag.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Flight/System/Dynamics/CentralBodyGravity.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Flight/System/Dynamics/ThirdBodyGravity.test.cpp
I found the boost header which has all the templates for VectorXd 👍
> refactor: remove boost from headers in NumericalSolver

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/NumericalSolver.cpp
- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/RootSolver.cpp
- bindings/python/test/test_numerical_solver.py
- bindings/python/test/test_root_solver.py
- bindings/python/thirdparty/boost_numpy_eigen/eigen_numpy.cpp
- include/OpenSpaceToolkit/Astrodynamics/EventCondition.hpp
- include/OpenSpaceToolkit/Astrodynamics/NumericalSolver.hpp
- include/OpenSpaceToolkit/Astrodynamics/RootSolver.hpp
- src/OpenSpaceToolkit/Astrodynamics/NumericalSolver.cpp
- src/OpenSpaceToolkit/Astrodynamics/RootSolver.cpp
- test/OpenSpaceToolkit/Astrodynamics/NumericalSolver.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/RootSolver.test.cpp
This PR proposes a naming realignment (for consistency w/ rest of codebase):
- `numberOfSomething` -> `somethingCount`
- `someObjectsCount` -> `someObjectCount`
On top, it fixes some typos in the documentation.
> fix: add naming suggestions

- Makefile
- bindings/python/docs/Demonstration/new-orbit-constructors.ipynb
- bindings/python/requirements.txt
- bindings/python/test/access/test_generator.py
- bindings/python/test/conjunction/messages/ccsds/test_cdm.py
- bindings/python/test/event_condition/test_coe_condition.py
- bindings/python/test/flight/profile/test_state.py
- bindings/python/test/flight/test_profile.py
- bindings/python/test/test_access.py
- bindings/python/test/test_converters.py
- bindings/python/test/test_display.py
- bindings/python/test/test_event_condition.py
- bindings/python/test/test_numerical_solver.py
- bindings/python/test/test_utilities.py
- bindings/python/test/test_viewer.py
- bindings/python/test/trajectory/orbit/models/kepler/test_coe.py
- bindings/python/test/trajectory/orbit/models/sgp4/test_tle.py
- bindings/python/test/trajectory/orbit/models/test_propagated.py
- bindings/python/test/trajectory/orbit/models/test_tabulated.py
- bindings/python/test/trajectory/test_propagator.py
- bindings/python/tools/python/ostk/astrodynamics/converters.py
- bindings/python/tools/python/ostk/astrodynamics/utilities.py
- bindings/python/tools/python/ostk/astrodynamics/viewer.py
- test/OpenSpaceToolkit/Astrodynamics/Access/Generator.test.cpp
This PR adds a 3D viewer based on [CesiumPy](https://github.com/lucas-bremond/cesiumpy) to the Python utilities, to simplify displaying Profiles in Python.
> feat: add CesiumPy Viewer to Python utilities

- Makefile
- bindings/python/test/conjunction/messages/ccsds/test_cdm.py
- bindings/python/test/event_condition/test_coe_condition.py
- bindings/python/test/flight/test_profile.py
- bindings/python/test/test_access.py
- bindings/python/test/test_converters.py
- bindings/python/test/test_event_condition.py
- bindings/python/test/test_numerical_solver.py
- bindings/python/test/test_viewer.py
- bindings/python/test/trajectory/orbit/models/kepler/test_coe.py
- bindings/python/test/trajectory/orbit/models/sgp4/test_tle.py
- bindings/python/test/trajectory/orbit/models/test_propagated.py
- bindings/python/test/trajectory/orbit/models/test_tabulated.py
- bindings/python/test/trajectory/test_propagator.py
This fixes the issue @kyle-cochran found with running `make format-python` locally.
I checked the /etc/group in the docker container and it doesn't contain our groups.
If you exec into the container it complains about this:
groups: cannot find name for group ID 1050
> build: fix format-python in makefile

- bindings/python/test/event_condition/test_coe_condition.py
- include/OpenSpaceToolkit/Astrodynamics/EventCondition/COECondition.hpp
- src/OpenSpaceToolkit/Astrodynamics/EventCondition/COECondition.cpp
- test/OpenSpaceToolkit/Astrodynamics/EventCondition/COECondition.test.cpp
Because of how the member variables were getting initialized, this would produce a segfault as it was getting captured in the lambda before initialization.
> fix: COECondition static construction

- CMakeLists.txt
- bindings/python/requirements.txt
- docker/development/Dockerfile
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Propagator.test.cpp
- tools/development/start.sh
Updates to OSTk Physics `v2.0`. Add some lightweight tests to the `Propagator.test.cpp` to try and generate states at the edge of where input data is available. Those limits are:
- 5 years in the past when propagating with drag
- 1 year in the future when doing ITRF/TEME frame conversions
(these don't cover all propagation cases obviously, but do flex the data handling which is the intent 😁).
TODO: this won't even build in CI until Physics 2.0 is released, but was cross-tested locally.
> feat: switch to physics v2.0 and add data validity range tests

- include/OpenSpaceToolkit/Astrodynamics/Flight/System/PropulsionSystem.hpp
- include/OpenSpaceToolkit/Astrodynamics/Flight/System/SatelliteSystem.hpp
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/State/CoordinatesSubset.hpp
- src/OpenSpaceToolkit/Astrodynamics/EventCondition/DurationCondition.cpp
- src/OpenSpaceToolkit/Astrodynamics/Flight/System/PropulsionSystem.cpp
- src/OpenSpaceToolkit/Astrodynamics/Flight/System/SatelliteSystem.cpp
- test/OpenSpaceToolkit/Astrodynamics/Flight/System/PropulsionSystem.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Flight/System/SatelliteSystem.test.cpp
- Adds a simple propulsionSystem (constant thrust, constant Isp) class to hold information about thrusting system. 
- No python bindings in this PR for now on purpose.
> feat: add simple PropulsionSystem class

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory/State.cpp
- bindings/python/test/trajectory/test_state.py
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/State.hpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/State.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/State.test.cpp
Exposing the list of subsets would be useful for the OD changes in FDS toolbox, so we don't have to pass around the original broker they were created with.
> feat: add getCoordinatesSubsets method to States

- src/OpenSpaceToolkit/Astrodynamics/Trajectory/State.cpp
When printing the State, you currently see:
```
-- Trajectory :: State -----------------------------------------------------------------------------
Instant:                                 2018-01-01 00:00:00 [UTC]                
Position:                                [1.200000000000, 3.400000000000, 5.600000000000] [m] @ GCRF 
Velocity:                                [7.800000000000, 9.000000000000, 1.200000000000] [m/s] @ GCRF 
----------------------------------------------------------------------------------------------------
```
This updates the print to support extending the state beyond position/velocity. So now it looks like:
```
-- Trajectory :: State -----------------------------------------------------------------------------
Instant: …
```
> feat: update State printing to support extended state

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory/State.cpp
- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory/State/CoordinatesBroker.cpp
- bindings/python/test/trajectory/state/test_coordinates_broker.py
- bindings/python/test/trajectory/test_state.py
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/State.hpp
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/State/CoordinatesBroker.hpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/State.cpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/State/CoordinatesBroker.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/State.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/State/CoordinatesBroker.test.cpp
Add 
`VectorXd State::extractCoordinates(const Array<Shared<const CoordinatesSubset>>& aCoordinatesSubsetsArray) const;`
and
```
VectorXd CoordinatesBroker::extractCoordinates(
const VectorXd& aFullCoordinatesVector, const Array<Shared<const CoordinatesSubset>>& aCoordinatesSubsetsArray
) const;
```
to allow extracting multiple subsets at once. 
This is a preliminary step for whatever State::contract/slice/etc. function we implement.
Also add doc-strings to the State class.
> feat: add functions to extract multiple subsets at once.

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory/State.cpp
- bindings/python/test/trajectory/test_state.py
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/State.hpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/State.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/State.test.cpp
Adds a constructor to the State class to directly build a custom State from an Array of Subsets.
This constructor will presumably cause a larger memory footprint, but is more straightforward to use than the Broker constructor.
This downfall should be mitigated in Python with the introduction of the CustomState meta-class stuff.
> feat: add State constructor with Array of Subsets

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory.cpp
- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory/StateBuilder.cpp
- bindings/python/test/trajectory/test_propagator.py
- bindings/python/test/trajectory/test_state_builder.py
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/State.hpp
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/StateBuilder.hpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/State.cpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/StateBuilder.cpp
- test/OpenSpaceToolkit/Astrodynamics/EventCondition/AngularCondition.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/EventCondition/BooleanCondition.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/EventCondition/RealCondition.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/State.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/StateBuilder.test.cpp
Adds a StateBuilder class to enable creating batches of States that share the same `Coordinates Broker`, without a user needing to interact with the `CoordinateBroker` concept at all.
The main function is 
- `StateBuilder::buildState(Instant, VectorXd)` [Cpp]
- `StateBuilder.state(Instant, np.ndarray)` [Python]
and the flow in Python looks like:
```python
builder: StateBuilder = StateBuilder(
Frame.gcrf(),
[CartesianPosition.default(), CartesianVelocity.default()]
)
start_instant = Instant.date_time(datetime(2022, 1, 1))
start_coords = np.array([1,2,3,4,5,6])
states = []
for i in range(100):
states.append(builder.state(
start_instant+Duration.seconds(i),
start_coords*i,
))
```
The MR is largely boilerplate copied from the `State` class. New functionality is mostly in the `buildState` …
> feat: add StateBuilder

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory/StateBuilder.cpp
- bindings/python/test/trajectory/test_state_builder.py
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/State/CoordinatesSubset.hpp
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/StateBuilder.hpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/State.cpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/StateBuilder.cpp
- test/OpenSpaceToolkit/Astrodynamics/EventCondition/AngularCondition.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/EventCondition/BooleanCondition.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/EventCondition/RealCondition.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/State.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/StateBuilder.test.cpp
Add `StateBuilder` features:
- StateBuilder +/- CoordinateSubset operators
- State reduction
- State expansion
Additional:
- Renaming `buildState` -> `build`
- Fix minor "bug" where `State` == comparator was not assessing number of coordinates
> feat: enrich StateBuilder capabilities

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory/State.cpp
- bindings/python/test/trajectory/test_state.py
- bindings/python/tools/python/ostk/astrodynamics/__init__.py
- bindings/python/tools/python/ostk/astrodynamics/pytrajectory/__init__.py
- bindings/python/tools/python/ostk/astrodynamics/pytrajectory/pystate.py
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/State.hpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/State.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/State.test.cpp
This MR is some Python-only syntactic sugar on top of the State Builder concept which allows for some nice syntax:
```python
MySuperFunState: type = State.template(
frame,
[CartesianPosition.default(), CartesianVelocity.default()],
)
states: MySuperFunState = [
MySuperFunState(instant,coords) for instant,coords in zip(instants, coordinates)
]
```
The output StateTypeX classes are polymorphic to State and so can be used anywhere a State can.
This example is 100% equivalent to using a builder and is just a syntax alternative.
(other meta-programming features like auto-assigning `state.mass` to get the mass value will be in a follow-up)
> feat: Python class meta-programming for State construction

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory/State.cpp
- bindings/python/test/trajectory/test_state.py
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/State.hpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/State.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/State.test.cpp
I find myself wanting to do this a lot:
```python
if state.has_subset(CartesianPosition.default()):
coords = state.extract_coordinates(CartesianPosition.default())
```
But it's currently only exposed at the coordinates broker level.
> feat: add hasSubset method to State

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Solvers/FiniteDifferenceSolver.cpp
- bindings/python/test/solvers/test_finite_difference_solver.py
- include/OpenSpaceToolkit/Astrodynamics/Solvers/FiniteDifferenceSolver.hpp
- src/OpenSpaceToolkit/Astrodynamics/Solvers/FiniteDifferenceSolver.cpp
- test/OpenSpaceToolkit/Astrodynamics/Solvers/FiniteDifferenceSolver.test.cpp
Updating the callable interface to return coordinates so that it's easier to generate the STM/Gradient. It's a bit annoying to create a state when we're only using the coordinates. Also, in cases like QLaw, we're finite differencing abstract concepts like the Q value where it doesn't make sense to create a fake state for it.
> feat: update finite difference solver callable interface

- src/OpenSpaceToolkit/Astrodynamics/Dynamics/Thruster.cpp
- test/OpenSpaceToolkit/Astrodynamics/Dynamics/Thruster.test.cpp
In the scenario that we return an acceleration that is < the thrust magnitude maximum we should scale the mass flow rate based on the effective thrust.
> feat: scale mass flow rate by thrust percentage

- Makefile
This MR aims to make the ostk dev experience better by streamlining the build/make process by improving the makefile:
- allow the `make debug-jupyter-notebook` target to build and cache the binaries for the locally modified source code everytime you run that command, instead of needing to spin up a development container and build/re-build before re-launching jupyter
- make clean now removes all build/lib/package/etc folders to actually clean things properly
The part that hasn't been done yet is to fix container users so that we aren't root inside the container, which causes issues when working inside and outside the container since the hosts' files are now changed owners. This might become a little difficult because CMake doesn't seem to like being run from a non-root user.
> chore: improve-makefile-and-dev-experience

- bindings/python/docs/Demonstration/Orbit Propagation.ipynb
- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/GuidanceLaw/QLaw.cpp
- bindings/python/test/guidance_law/test_qlaw.py
- include/OpenSpaceToolkit/Astrodynamics/GuidanceLaw/QLaw.hpp
- src/OpenSpaceToolkit/Astrodynamics/GuidanceLaw/QLaw.cpp
- test/OpenSpaceToolkit/Astrodynamics/Access/Generator.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/GuidanceLaw/QLaw.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Propagator.test.cpp
We should absolutely not review the functions that are calculating the analytical derivatives, it's a lot of code.
Instead if someone can use sympy to calculate the analytical derivatives and confirm that they are producing similar numbers for the same inputs, that would be great. Or you can double check my math in this script:
```
from sympy import symbols, diff, sin, cos, sqrt, exp, Abs, acos, cse
import numpy as np
from sympy.printing.cxx import CXX17CodePrinter
(
a,
e,
i,
raan,
aop,
v,
aT,
eT,
iT,
raanT,
aopT,
thrust_acceleration,
WP,
rpmin,
m_scale,
n_scale,
r_scale,
k_scale,
b_scale,
mu,
W_a,
W_e,
W_i,
W_raan,
W_aop,
) = symbols(
"semiMajorAxis eccentricity inclination rightAscensionOfAscendingNode argumentOfPeriapsis trueAnomaly semiMajorAxisTarget eccentricityTarget …
```
> feat: use analytical derivatives for QLaw

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/GuidanceLaw/QLaw.cpp
- include/OpenSpaceToolkit/Astrodynamics/GuidanceLaw/QLaw.hpp
- src/OpenSpaceToolkit/Astrodynamics/GuidanceLaw/QLaw.cpp
- test/OpenSpaceToolkit/Astrodynamics/GuidanceLaw/QLaw.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Propagator.test.cpp
This allows us to trade time of flight with fuel mass. It will force some coast arcs so that we burn at "optimal" points in the orbit.
> feat: relative/absolute effectivity thresholds for QLaw

- src/OpenSpaceToolkit/Astrodynamics/GuidanceLaw/QLaw.cpp
> chore: use eta variables for return statement to remove build warning

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory/State/NumericalSolver.cpp
- bindings/python/test/trajectory/state/test_numerical_solver.py
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/State/NumericalSolver.hpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/State/NumericalSolver.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/State/NumericalSolver.test.cpp
This adds a static constructor to enable the creation of a fixed step size numerical solver with the RK4 stepper type like so:
```
solver = NumericalSolver.fixed_step_size(RK4, 30.0)
```
> feat: add fixed step size factory method for numerical solver

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory/Segment.cpp
- bindings/python/test/trajectory/test_segment.py
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/Segment.hpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/Segment.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Segment.test.cpp
- `getDynamicsContribution` method allowing to compute the contribution of a `Dynamics` attached to the Segment Solution for a `Frame`, `Dynamics` and optional subset of `CoordinatesSubset` attached to Dynamics write coordinates Subset. 
- `getAllDynamicsContributions` method leveraging the first method and returning on Map of contributions Matrices for all dynamics of the Segment Solution. 
- `getAccelerationDynamicsContribution` method leveraging the first method and returning the acceleration contribution only of a Dynamics.
> feat: add dynamics contribution getters to segment solution

- .devcontainer/devcontainer.json
- .github/workflows/build-test.yml
- Makefile
- docker/development/Dockerfile
- tools/development/start.sh
This PR adds a nicer interface for our local dev container as non-root user and eliminates volume sharing permissions issues associated with build folders having root permissions when you exit the dev container.
This MR depends on this one https://github.com/open-space-collective/open-space-toolkit/pull/81 to be merged first and a new version of the ostk-base image to be pushed to docker hub.
> chore: improve dev container with non-root access 

- docker/development/Dockerfile
Tiny change to use the slightly cleaner syntax for setting the OSTk data environment.
> build: use the shorthand seed data env var

- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Propagator.test.cpp
The OSTk test image takes a bit to include the CSSI space weather rollover. Extend the failure look point a couple months to give it a little wiggle room.
> test: update past data expectation with wiggle room for CSSI rollover

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Flight/System/SatelliteSystemBuilder.cpp
- include/OpenSpaceToolkit/Astrodynamics/Flight/System/SatelliteSystemBuilder.hpp
- src/OpenSpaceToolkit/Astrodynamics/Flight/System/PropulsionSystem.cpp
It seems there was an error before, and anyways, I think all three mem vars `thrust_`, `specificImpulse_`, and `massFlowRate_` should remain undefined (as defaulted in the .hpp) if the input scalars are not defined.
> fix: update Propulsion System scalar constructor

- docker/development/Dockerfile
This MR adds:
- changes ownership of the ostk-data folder to the non-root user, otherwise anything that uses that folder fails
- adds ssh to the dev container so that you can push to git from within the dev container
- adds a default .zshrc config file
> fix: non-root dev container ostk data issue

- bindings/python/test/test_converters.py
- bindings/python/tools/python/ostk/astrodynamics/converters.py
- ✅ Enrich conversion to `datetime` and `Instant` to consider ISO strings
- ✅ Create a `coerce_to_iso` for `datetime`, `Instant` and ISO strings
- ✅ Fix `datetime` to `Instant` conversion where scale was assumed to be in UTC
- ✅ Enriched tests
> feat: enrich and fix time conversion functions

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory/Segment.cpp
- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory/Sequence.cpp
- bindings/python/test/trajectory/test_segment.py
- bindings/python/test/trajectory/test_sequence.py
- include/OpenSpaceToolkit/Astrodynamics/Conjunction/Messages/CCSDS/CDM.hpp
- include/OpenSpaceToolkit/Astrodynamics/EventCondition/InstantCondition.hpp
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit/Models/Propagated.hpp
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/Propagator.hpp
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/Segment.hpp
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/Sequence.hpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/Segment.cpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/Sequence.cpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/State/NumericalSolver.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Segment.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Sequence.test.cpp
This MR adds a `reComputeStatesAt(instant,numericalSolver)` method to the `Sequence` and `Segment` objects.
This specific method is needed for my validation framework because when the sequence is first solved, it is done so with a variable step size propagator since the event conditions can't be known ahead of time. Therefore, the states that are "observed" and stored in the `Segment` object are at random timestamps corresponding to the variable steps the propagator took. 
I want to be able to obtain the propagated states at an arbitrary instant array in order to be able to compare them with states generated by GMAT or Orekit at those same instants. Therefore, the only option here is to re-propagate the states in a rather dumb and not efficient way after the segment has been solved and …
> feat: add repropagation of intermediate states to sequence and segment

- src/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit.test.cpp
Previously, the index being returned is the first state within the pass.
This is a bit awkward when looping over it, as you need the index from the second pass to find the states that are within the first pass.
Instead here I propose having the end state index be returned with the pass.
That way, we can conveniently (in python) do the following:
current_index = 0
for index, pass in pass_map.items():
pass_states = states[current_index : index]
index = current_index
....
> refactor: change the index returned by pass map to be the last index

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory/Orbit.cpp
- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory/Orbit/Pass.cpp
- bindings/python/test/trajectory/orbit/test_pass.py
- bindings/python/test/trajectory/test_orbit.py
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit.hpp
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit/Pass.hpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit.cpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit/Pass.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit/Pass.test.cpp
The main lift here is having explicit definitions for all the parameters for a Pass. This was necessary as a Pass can be partial from both sides:
```
|        ----------------|
|--------------          |
```
Therefore we want explicit definitions for the ascending node, north point, descending node, south point and the pass break.
Where pass break is the ascending node for the _next_ pass.
This is also necessary to properly define whether the pass is complete or partial.
Note: While there are some breaking changes here, since this function was recently released and is not used anywhere (yet) we don't necessarily have to do a major version increase here.
> feat: update pass constructor to allow partial passes from start/end

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Flight/System/PropulsionSystem.cpp
- bindings/python/test/flight/system/test_propulsion_system.py
- bindings/python/test/guidance_law/test_qlaw.py
- include/OpenSpaceToolkit/Astrodynamics/Flight/System/PropulsionSystem.hpp
- include/OpenSpaceToolkit/Astrodynamics/GuidanceLaw/ConstantThrust.hpp
- src/OpenSpaceToolkit/Astrodynamics/Dynamics/AtmosphericDrag.cpp
- src/OpenSpaceToolkit/Astrodynamics/Dynamics/CentralBodyGravity.cpp
- src/OpenSpaceToolkit/Astrodynamics/Dynamics/PositionDerivative.cpp
- src/OpenSpaceToolkit/Astrodynamics/Dynamics/ThirdBodyGravity.cpp
- src/OpenSpaceToolkit/Astrodynamics/Dynamics/Thruster.cpp
- src/OpenSpaceToolkit/Astrodynamics/Flight/System/PropulsionSystem.cpp
- test/OpenSpaceToolkit/Astrodynamics/Flight/System/PropulsionSystem.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Flight/System/SatelliteSystem.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Flight/System/SatelliteSystemBuilder.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/GuidanceLaw/ConstantThrust.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/GuidanceLaw/QLaw.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Propagator.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Sequence.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Validation/NRLMSIS00.validation.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Validation/Propagator.cross.validation.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Validation/Propagator.self.validation.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Validation/QLaw.validation.cpp
- validation/OpenSpaceToolkit/Astrodynamics/Framework.validation.cpp
- validation/OpenSpaceToolkit/Astrodynamics/Parser.hpp
- validation/OpenSpaceToolkit/Astrodynamics/Parser.test.cpp
After going down a rabbit hole of trying to add python bindings for the `physics::data::Scalar` class (which currently lacks them) in OSTk physics, I have deemed that much harder than it seems on the surface and come up with an alternative medium term solution.
Context on the cpp side for OSTk physics:
- There is lots of convoluted code deep down inside of physics::Unit, which would take a non-trivial amount of time to modify if needed
- the tests for physics::Unit are weak, and the tests for physics::unit::Derived are non-existant (which is scary because we use physics::unit::Derived in a lot of places in astro
- the tests for data::Scalar and data::Vector and data::Direction are non-existant
- all derived units should be defined inside of physics::Unit, not as the Thrust and …
> refactor: propulsion system to use Reals instead of Scalar

- .github/workflows/benchmark-validation.yml
- .github/workflows/build-test.yml
- .github/workflows/release.yml
This should fix the issue with the benchmark and validation job on main being cancelled because it is running concurrently with the build-test job
> chore: move benchmark and validation tests to separate CI

- include/OpenSpaceToolkit/Astrodynamics/Trajectory/Propagator.hpp
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/State/CoordinateBroker.hpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit/Model/Propagated.cpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/Propagator.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit/Model/Propagated.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Propagator.test.cpp
This MR refactors the propagator slightly by adding some dynamics validation logic so that propagation can't be done with a set of dynamics that doesn't make sense. 
- It defines a maximum and minimum number of each type of dynamics that can be used for propagation in a map, and perform a "propagation-time" check that occurs as the first step of the `calculateXAt()` methods being called, so that the user can add whatever dynamics they want one by one and/or remove dynamics using `.addDynamics` and `.setDynamics` and `.clearDynamics` until they have a good dynamics set, which is only validated before it will actually be used to calculate a state.
This MR refactors the `Propagator` unit tests in some places to be more concise, and also adds a deep copy constructor and deep copy assignement …
> refactor: add dynamics validation to propagator

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Flight/Maneuver.cpp
- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory/Propagator.cpp
- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory/Segment.cpp
- bindings/python/test/dynamics/test_tabulated.py
- bindings/python/test/flight/test_maneuver.py
- bindings/python/test/trajectory/test_propagator.py
- bindings/python/test/trajectory/test_segment.py
- include/OpenSpaceToolkit/Astrodynamics/Flight/Maneuver.hpp
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/Propagator.hpp
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/Segment.hpp
- src/OpenSpaceToolkit/Astrodynamics/Flight/Maneuver.cpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/Propagator.cpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/Segment.cpp
- test/OpenSpaceToolkit/Astrodynamics/Flight/Maneuver.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Propagator.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Segment.test.cpp
This MR will connect the `Maneuver` class from[ this MR](https://github.com/open-space-collective/open-space-toolkit-astrodynamics/pull/333) to other classes in OSTk in order to be leverage with them. This MR adds methods to add extract maneuvers from a `SegmentSolution` once it has been solved and then repopagate over them seemlessly with the  `Propagator` by allow it to have maneuvers added to its dynamics as `TabulatedDynamics`. 
Progress:
> feat: connect maneuver class with segments and propagator

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Dynamics/Tabulated.cpp
- bindings/python/test/dynamics/test_tabulated.py
- bindings/python/test/flight/test_maneuver.py
- include/OpenSpaceToolkit/Astrodynamics/Dynamics/Tabulated.hpp
- src/OpenSpaceToolkit/Astrodynamics/Dynamics/Tabulated.cpp
- src/OpenSpaceToolkit/Astrodynamics/Flight/Maneuver.cpp
- test/OpenSpaceToolkit/Astrodynamics/Dynamics/Tabulated.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Flight/Maneuver.test.cpp
This MR is in response to @phc1990 's comment [here](https://github.com/open-space-collective/open-space-toolkit-astrodynamics/pull/340#discussion_r1500867108) about adding a `getContributionProfileFromCoordinateSubsets` to TabulatedDynamics as a stopgap to properly refactoring the way Dynamics are handled (and expanded and reduced) in the future.
Also I removed the redundant getters in `TabulatedDynamics` to keep with the pattern:
- accessors for member variables
- getters for member variables that you modify before returning or anything computed on the fly
> refactor!: tabulated dynamics getters into accessors only and add a specific getter for returning a matrixxd from coordinate subsets

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Flight/Maneuver.cpp
- bindings/python/test/flight/test_maneuver.py
- include/OpenSpaceToolkit/Astrodynamics/Flight/Maneuver.hpp
- src/OpenSpaceToolkit/Astrodynamics/Dynamics/Tabulated.cpp
- src/OpenSpaceToolkit/Astrodynamics/Flight/Maneuver.cpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/Segment.cpp
- test/OpenSpaceToolkit/Astrodynamics/Flight/Maneuver.test.cpp
Small MR to address @vishwa2710's comment on the Maneuver class' interface with other OSTk objects on these two MRs:
https://github.com/open-space-collective/open-space-toolkit-astrodynamics/pull/340
https://github.com/open-space-collective/open-space-toolkit-astrodynamics/pull/365
> refactor!:small changes to maneuver class based on vishwa's suggestions

- CMakeLists.txt
- Makefile
- bindings/python/CMakeLists.txt
- bindings/python/requirements.txt
- bindings/python/tools/python/setup.cfg.in
- docker/development/Dockerfile
Added platform specific definitions, and updated Dockerfile for development with new versions and base image.
- Requires merge of https://github.com/open-space-collective/open-space-toolkit-core/pull/153 and ostk-core 3.0.0 release before passing
- Requires merge of https://github.com/open-space-collective/open-space-toolkit-io/pull/82 and ostk-io 3.0.0 release before passing
- Requires merge of https://github.com/open-space-collective/open-space-toolkit-mathematics/pull/121 and ostk-math 3.0.0 release before passing
- Requires merge of https://github.com/open-space-collective/open-space-toolkit-physics/pull/222 and ostk-physics 6.0.0 release before passing
Needs to be relased as ostk-astrodynamics 9.0.0
> feat: Refactored CMakeLists, updated versions for OSTk Dependencies

- include/OpenSpaceToolkit/Astrodynamics/Flight/Maneuver.hpp
- src/OpenSpaceToolkit/Astrodynamics/Flight/Maneuver.cpp
- test/OpenSpaceToolkit/Astrodynamics/Flight/Maneuver.test.cpp
Part of Maneuver validation effort.
This MR:
> feat: add incorrect maneuver construction warnings and asserts

- src/OpenSpaceToolkit/Astrodynamics/Trajectory/State/CoordinateSubset.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/State/CoordinateSubset.test.cpp
Users can create a `CoordinateSubset`, giving it a specific name and number of coordinates in the subset. However, if they use the `inFrame` conversion method on the `CoordinateSubset` class itself, it doesn't actually do the conversion they want, it just returns the coordinates as they are.
This is fine for scalar subsets, but not fine for vector coordinate subsets because it is a hidden behavior the user may not be aware of. Therefore, if someone tries to do this, I will raise an error.
If the user wants to make their own non-scalar coordinate subset by inheriting from `CoordinateSubset`, then they can get around this error by acutally implementing the `virtual` `inFrame` method and overriding it in their child class.
> fix: coordinate subset unsafe frame conversion

- benchmark/OpenSpaceToolkit/Astrodynamics/Propagation.benchmark.cpp
- include/OpenSpaceToolkit/Astrodynamics/Dynamics/Tabulated.hpp
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit/Model/Propagated.hpp
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/Propagator.hpp
- src/OpenSpaceToolkit/Astrodynamics/Dynamics/Tabulated.cpp
- src/OpenSpaceToolkit/Astrodynamics/Flight/Maneuver.cpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit/Model/Propagated.cpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/Propagator.cpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/Segment.cpp
- test/OpenSpaceToolkit/Astrodynamics/Dynamics/Tabulated.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Propagator.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Validation/Propagator.cross.validation.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Validation/Propagator.self.validation.cpp
Part of Maneuver validation effort.
This MR:
> feat: add maneuver cross and self validation

- bindings/python/test/flight/test_maneuver.py
- bindings/python/test/test_utilities.py
- bindings/python/tools/python/ostk/astrodynamics/converters.py
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/Segment.hpp
- src/OpenSpaceToolkit/Astrodynamics/Flight/Maneuver.cpp
- src/OpenSpaceToolkit/Astrodynamics/GuidanceLaw/QLaw.cpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/Segment.cpp
- test/OpenSpaceToolkit/Astrodynamics/Flight/Maneuver.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Segment.test.cpp
Part of Maneuver validation effort.
This MR:
> feat: improve SegmentSolution's maneuver extracting algorithm and Maneuver's calculate methods

- docs/python.rst
> docs: add python-only tools to docs

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory/State/CoordinateSubset.cpp
- bindings/python/test/trajectory/state/test_coordinate_subset.py
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/State/CoordinateSubset.hpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/State/CoordinateSubset.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/State/CoordinateSubset.test.cpp
This will allow us to use `CoordinateSubset` as a key in a python dictionary in our services
> feat: make coordinate subsets hashable

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory/Orbit.cpp
- bindings/python/test/trajectory/test_orbit.py
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit.hpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit.test.cpp
Parametrize the step size when computing passes.
As mentioned in the comments this was a [TBM].
The duration based step size was too big for long orbits and was causing revolutions to get skipped.
> feat: add duration step parameter to Orbit.getPassWithRevolutionNumber

- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory/Orbit.cpp
- include/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit.hpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/State.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/State.test.cpp
We are not performing subset-to-subset +/- operations at the moment whenever a State +/- operation is carried out.
This MR fails when attempting to perform a +/- operations between states where the underlying coordinate subsets are not in the same and in the same order.
> fix: prevent State addition and subtraction based on coordinates broker not being equal

- bindings/python/requirements.txt
- bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Trajectory.cpp
- bindings/python/test/test_trajectory.py
- include/OpenSpaceToolkit/Astrodynamics/Trajectory.hpp
- src/OpenSpaceToolkit/Astrodynamics/GuidanceLaw/QLaw.cpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory.cpp
- src/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit/Model/Kepler/COE.cpp
- test/OpenSpaceToolkit/Astrodynamics/GuidanceLaw/QLaw.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Orbit/Model/Kepler/COE.test.cpp
- test/OpenSpaceToolkit/Astrodynamics/Trajectory/Validation/QLaw.validation.cpp
This MR adds a static constructor for the Trajectory class for a ground strip. This is useful in conjunction with the Profile::TrajectoryTarget object where we want to create a Profile during a ground strip is tracked, in Earth observation applications.
> feat: Trajectory constructor based on a ground strip

- bindings/python/CMakeLists.txt
- bindings/python/tools/python/ostk/astrodynamics/pytrajectory/pystate.py
Adds automated stub generation and bundling into the wheels. Requires [open-space-toolkit >= 0.8.3](https://github.com/open-space-collective/open-space-toolkit/releases/tag/0.8.3) due to the apt-installed numpy being incompatible with pybind11-stubgen.
Additionally, changed the `staticmethod` markers from decorators to functions. This is because in Python 3.9, pybind11-stubgen will throw the following error: 
<details><summary>Traceback</summary>
```
Traceback (most recent call last):
File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.9/dist-packages/pybind11_stubgen/__main__.py", line 4, in <module>
main()
File …
```
> chore: package stubs in whl

- CMakeLists.txt
- bindings/python/requirements.txt
- bindings/python/tools/python/setup.cfg.in
- docker/development/Dockerfile
- docker/jupyter/Dockerfile
- docker/release/Dockerfile
- tutorials/cpp/sensor-modeling/Dockerfile
In addition to the changes [described here](https://github.com/open-space-collective/open-space-toolkit-core/pull/181), also bumps the ostk-core dependency to 5.0 following [its release](https://github.com/open-space-collective/open-space-toolkit-core/releases/tag/5.0.0) (no breaking changes expected for this repo), and bumps Boost to 1.87 following the [bump in the base image](https://github.com/open-space-collective/open-space-toolkit/releases/tag/0.8.4).
>  chore: fix dockerfile and setuptools warnings, bump ostk-core and boost 
